### ISSUE TITLE
Solution code was added to the main branch.

### ISSUE THREAD

**Issue by QSissler** [learn-co-curriculum/python-p3-cartoon-collections-lab#1]
### Canvas Link

https://learning.flatironschool.com/courses/6049/assignments/208597?module_item_id=480930

### Concern

The cartoon_collections.py file on the main branch was recently updated to include solution code.

### Suggested Changes

Remove code so students are starting with a blank file.

**Comment by lizbur10** [comment]
Thanks @QSissler ! This has been fixed 💙
